version: "3.8"
services:
  forum-app:
    container_name: "forum-app"
    image: "forum-app"
    build:
      context: .
      dockerfile: "build/Dockerfile"
    ports:
      - "8000:8000"
    restart: "on-failure"
    environment:
      - PGSQL_HOST=host.docker.internal
      - PGSQL_PORT=3306
      - PGSQL_USERNAME=root
      - PGSQL_PASSWORD=root
      - PGSQL_DBNAME=forumdb